### PR TITLE
Capable robot cq1 pythonocc

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@osterwood  @justbuchanan could you help me verifying that this PR works with cqparts?

**Comment by justbuchanan** [comment]
I tried it out and in combination with the capablerobot fork of cqparts, it seems to work really well. There are still some cqparts tests failing, but I think those can be fixed separately from what's in this PR. We'll also need to make some more changes to cqparts as well. For reference, I attached the test log below.

I used this branch of cadquery plus a [few hacks](https://github.com/justbuchanan/cq-editor/tree/cqparts-hacks) and managed to get cqparts assemblies rendering in cq-editor. Here's a screenshot of the [toy car example](https://github.com/fragmuffin/cqparts/blob/master/docs/doc/_static/iframes/toy-car/generate.py) from cqparts.

cqparts-cq-editor


[cqparts-occ-test.log](https://github.com/adam-urbanczyk/cadquery/files/2498644/cqparts-occ-test.log)

**Comment by adam-urbanczyk** [comment]
Wow, that looks great. I am going to merge.

BTW: I see quite some errors on the cqparts side related to direct usage of FreeCAD/.wrapped . That should easy to fix.

**Comment by adam-urbanczyk** [comment]
Wow, that looks great. I am going to merge.

BTW: I see quite some errors on the cqparts side related to direct usage of FreeCAD/.wrapped . That should easy to fix.

**Pull request merged**
