### PR TITLE
Trying to merge back cqparts related commits

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@justbuchanan any thoughts? Is this interesting for you?

I am not yet a cqparts user, but given the interest I'd like to merge back this functionality.

@osterwood is numpy really necessary? I think I'll rework to use the OCC matrix class (gp_Mat).

**Comment by justbuchanan** [comment]
This looks great! I started down a similar path trying to get cadquery-occ and cqparts to work together, but this looks more complete than what I've done so far. I'd be happy to help out with this however I can.

**Comment by osterwood** [comment]
It should be easy enough to use gp_Mat instead of nump -- there are only a few methods I used (shape, transpose, flatten).  

It's been a few months so my memory is a bit hazy, but I think I tried that path first and kept running into issues -- but I can't remember what they were at all.  I suspect someone more familiar with gp_Mat wouldn't run into the problems I did.

**Comment by adam-urbanczyk** [comment]
OK I moved this to #6

**Pull request closed without merging**
